### ISSUE TITLE
Stash with Redis-clustr

### ISSUE THREAD

**Issue by sharpn** [gosquared/stash#7]
Hey,

We are trying to use stash with redis-clustr and everytime it tries to connect it errors out with couldn't get subscriber client, after looking into the code the only reason i can see that this is happening is because none of the clients are currently ready.

Is this possible and if so is there an example

Nick

**Comment by sharpn** [comment]
Thanks for the reply.

We are creating the cluster with an ip address already.

**Comment by aadi99999** [comment]
Has this issue fixed ?
I am making a connection to the cluster via  hostname.
